// Ed25519 public key used to verify license signatures (offline).
// Generated by scripts/keygen.mjs. The matching private key lives only in
// scripts/.license-private.key (gitignored) and never ships with the plugin.
export const LICENSE_PUBLIC_KEY = "OATJwdDzi1ulsH9XHJd4z3P_yflngnhWaFszfEvMGsQ";
