// Ed25519 public key used to verify license signatures (offline).
// Generated by scripts/keygen.mjs. The matching private key lives only in
// scripts/.license-private.key (gitignored) and never ships with the plugin.
export const LICENSE_PUBLIC_KEY = "5mo8rQSqI7nHL-B6OgY_I9Tc5X6vUo1YqbRPa2zs6TM";
